# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "32ae6506402553d77b71df6408e4dee0"
name = "Contract Signing"
handle = "contract-signing"
application_url = "https://new-pos-app.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://new-pos-app.onrender.com/auth/callback", "https://new-pos-app.onrender.com/auth/shopify/callback", "https://new-pos-app.onrender.com/api/auth/callback"]

[pos]
embedded = false
