# The version of APIs your extension will receive. Learn more: 
# https://shopify.dev/docs/api/usage/versioning 
api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "pos-ui-contract-signing"

handle = "pos-ui-contract-signing"
description = "Cart Extension"

# Cart line item details targets (available in 2025-07)
[[extensions.targeting]]
module = "./src/Action.jsx"
target = "pos.cart.line-item-details.action.render"


[[extensions.targeting]]
module = "./src/MenuItem.jsx"
target = "pos.cart.line-item-details.action.menu-item.render"
