# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "pos-ui-draft-order-details"

handle = "pos-ui-draft-order-details"
description = "Contract Signing"

# Controls where in POS your extension will be injected,
# and the file that contains your extension’s source code.


[[extensions.targeting]]
module = "./src/Block.jsx"
target = "pos.draft-order-details.block.render"


